runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install prerequisites for pystack
      run: sudo apt-get install --no-install-recommends -qy libdw-dev libelf-dev
      shell: bash

    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        cache-environment: true
        init-shell: bash

    - name: Install dev requirements
      run: |
        micromamba run -n modyn pip install -e .
        micromamba run -n modyn pip install -r dev-requirements.txt
      shell: bash -l {0}
