# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import offline_pb2 as offline__pb2


class MetadataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetData = channel.unary_unary(
            '/offline.Metadata/GetData',
            request_serializer=offline__pb2.BatchData.SerializeToString,
            response_deserializer=offline__pb2.Data.FromString,
        )


class MetadataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetadataServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetData': grpc.unary_unary_rpc_method_handler(
            servicer.GetData,
            request_deserializer=offline__pb2.BatchData.FromString,
            response_serializer=offline__pb2.Data.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'offline.Metadata', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


class Metadata(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetData(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/offline.Metadata/GetData',
            offline__pb2.BatchData.SerializeToString,
            offline__pb2.Data.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)
