# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: offline.proto
"""Generated protocol buffer code."""
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\roffline.proto\x12\x07offline\x1a\x1cgoogle/protobuf/struct.proto\"5\n\tBatchData\x12(\n\x07\x64\x61taMap\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"0\n\x04\x44\x61ta\x12(\n\x07\x64\x61taMap\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2:\n\x08Metadata\x12.\n\x07GetData\x12\x12.offline.BatchData\x1a\r.offline.Data\"\x00\x62\x06proto3')  # noqa

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'offline_pb2', globals())
if not _descriptor._USE_C_DESCRIPTORS:

    DESCRIPTOR._options = None
    _BATCHDATA._serialized_start = 56
    _BATCHDATA._serialized_end = 109
    _DATA._serialized_start = 111
    _DATA._serialized_end = 159
    _METADATA._serialized_start = 161
    _METADATA._serialized_end = 219
# @@protoc_insertion_point(module_scope)
