ci:
  autoupdate_commit_msg: "chore: Update pre-commit hooks"
exclude: ^(\.data/|\.scratch/)
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.1"
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      # TODO: enable in followup PR, causes too many changes
      # - id: ruff-format
        # types_or: [python, pyi, jupyter]
  - repo: https://github.com/Quantco/pre-commit-mirrors-black
    rev: 24.4.2
    hooks:
      - id: black-conda
        args:
          - --safe
          - --target-version=py311
          - --config=pyproject.toml

  # - repo: local
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       entry: pylint
  #       language: system
  #       types: [python]
  #       require_serial: true
  #       args:
  #         [
  #           "-rn", # Only display messages
  #         ]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.9.0"
  #   hooks:
  #     - id: mypy
  #       additional_dependencies:
  #         [types-setuptools, types-pyyaml, types-requests]
  # - repo: https://github.com/Quantco/pre-commit-mirrors-prettier
  #   rev: 3.2.5
  #   hooks:
  #     - id: prettier-conda
  #       files: "\\.(md|json|yml|yaml)$"
  # - repo: https://github.com/myint/docformatter
  #   rev: v1.7.5
  #   hooks:
  #     - id: docformatter
  # - repo: https://github.com/sqlfluff/sqlfluff
  #   rev: 3.0.3
  #   hooks:
  #     - id: sqlfluff-fix
  # - repo: https://github.com/crate-ci/typos
  #   rev: v1.20.9
  #   hooks:
  #     - id: typos
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.5.0
  #   hooks:
  #     - id: trailing-whitespace
  #     - id: end-of-file-fixer
  #     - id: check-merge-conflict
  #       args: ["--assume-in-merge"]
