
[tool.black]
line-length = 120
target-version = ['py311']
extend-exclude = '''
(
    .*/.*\.pyi
  | .*/.*_grpc\.py
  | .*/.*_pb2\.py
  | .*/generated/
  | .*/build/
  | .*/libbuild/
  | .*/clang-tidy-build/
)
'''
