version: '3.8'

# By default, we disable mountain the current directory under /modyn_host. However, this might be helpful for local development.
# For the trainer server, you additionally might want to enable the runtime and deployment option to enable the GPU in the container.
# For the storage, you probably want to mount some volume containing the datasets.
# For the selector, you might want to mount a volume on a fast local storage device to store the trigger training sets.
# For storage-db and metadata-db, you might want to increase the amount of available /dev/shm and store the postgres files on a fast local disk.

services:
  metadata-db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: md5
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
#    shm_size: 24gb
    ports:
      - 22432:5432
    volumes:
      - .data/metadata-postgres-data:/var/lib/postgresql/data
      - .data/../:/modyn_all/
      - ./conf/metadata_postgresql.conf:/etc/postgresql/postgresql.conf
      - ./conf/pg_hba.conf:/tmp/pg_hba.conf
      - ./conf/init_pg_hba.sh:/docker-entrypoint-initdb.d/init_pg_hba.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
  storage-db:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - 22431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: md5
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
#    shm_size: 8gb
    volumes:
      - .data/storage-postgres-data:/var/lib/postgresql/data
      - .data/../:/modyn_all/
      - ./conf/storage_postgresql.conf:/etc/postgresql/postgresql.conf
      - ./conf/pg_hba.conf:/tmp/pg_hba.conf
      - ./conf/init_pg_hba.sh:/docker-entrypoint-initdb.d/init_pg_hba.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
volumes:
  storage-data:
  selector-data:
  selector-localstorage-data:
  downsampling-data:
  model_storage-data:
  supervisor-evaluation-data:
