# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: newqueue.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enewqueue.proto\x12\x08newqueue\"\x1f\n\x0eGetNextRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\"\x1f\n\x0fGetNextResponse\x12\x0c\n\x04keys\x18\x02 \x03(\t\"\x19\n\nAddRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\r\n\x0b\x41\x64\x64Response2\x82\x01\n\x08NewQueue\x12@\n\x07GetNext\x12\x18.newqueue.GetNextRequest\x1a\x19.newqueue.GetNextResponse\"\x00\x12\x34\n\x03\x41\x64\x64\x12\x14.newqueue.AddRequest\x1a\x15.newqueue.AddResponse\"\x00\x62\x06proto3')  # noqa: E501

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'newqueue_pb2', globals())
if not _descriptor._USE_C_DESCRIPTORS:

    DESCRIPTOR._options = None
    _GETNEXTREQUEST._serialized_start = 28
    _GETNEXTREQUEST._serialized_end = 59
    _GETNEXTRESPONSE._serialized_start = 61
    _GETNEXTRESPONSE._serialized_end = 92
    _ADDREQUEST._serialized_start = 94
    _ADDREQUEST._serialized_end = 119
    _ADDRESPONSE._serialized_start = 121
    _ADDRESPONSE._serialized_end = 134
    _NEWQUEUE._serialized_start = 137
    _NEWQUEUE._serialized_end = 267
# @@protoc_insertion_point(module_scope)
