# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trainer_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trainer_server.proto',
  package='trainer',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14trainer_server.proto\x12\x07trainer\"\x8b\x02\n\x14TrainerServerRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x39\n\x0fhyperparameters\x18\x02 \x01(\x0b\x32 .trainer.TrainingHyperparameters\x12\x17\n\x0f\x63heckpoint_path\x18\x03 \x01(\t\x12R\n\x13model_configuration\x18\x04 \x03(\x0b\x32\x35.trainer.TrainerServerRequest.ModelConfigurationEntry\x1a\x39\n\x17ModelConfigurationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\",\n\x15TrainerServerResponse\x12\x13\n\x0btraining_id\x18\x01 \x01(\x05\"D\n\x17TrainingHyperparameters\x12\x12\n\nbatch_size\x18\x01 \x01(\x05\x12\x15\n\rlearning_rate\x18\x02 \x01(\x02\x32\x62\n\rTrainerServer\x12Q\n\x0estart_training\x12\x1d.trainer.TrainerServerRequest\x1a\x1e.trainer.TrainerServerResponse\"\x00\x62\x06proto3'
)




_TRAINERSERVERREQUEST_MODELCONFIGURATIONENTRY = _descriptor.Descriptor(
  name='ModelConfigurationEntry',
  full_name='trainer.TrainerServerRequest.ModelConfigurationEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='trainer.TrainerServerRequest.ModelConfigurationEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='trainer.TrainerServerRequest.ModelConfigurationEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=301,
)

_TRAINERSERVERREQUEST = _descriptor.Descriptor(
  name='TrainerServerRequest',
  full_name='trainer.TrainerServerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_id', full_name='trainer.TrainerServerRequest.model_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hyperparameters', full_name='trainer.TrainerServerRequest.hyperparameters', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='checkpoint_path', full_name='trainer.TrainerServerRequest.checkpoint_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_configuration', full_name='trainer.TrainerServerRequest.model_configuration', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TRAINERSERVERREQUEST_MODELCONFIGURATIONENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=301,
)


_TRAINERSERVERRESPONSE = _descriptor.Descriptor(
  name='TrainerServerResponse',
  full_name='trainer.TrainerServerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='training_id', full_name='trainer.TrainerServerResponse.training_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=347,
)


_TRAININGHYPERPARAMETERS = _descriptor.Descriptor(
  name='TrainingHyperparameters',
  full_name='trainer.TrainingHyperparameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='trainer.TrainingHyperparameters.batch_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='trainer.TrainingHyperparameters.learning_rate', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=417,
)

_TRAINERSERVERREQUEST_MODELCONFIGURATIONENTRY.containing_type = _TRAINERSERVERREQUEST
_TRAINERSERVERREQUEST.fields_by_name['hyperparameters'].message_type = _TRAININGHYPERPARAMETERS
_TRAINERSERVERREQUEST.fields_by_name['model_configuration'].message_type = _TRAINERSERVERREQUEST_MODELCONFIGURATIONENTRY
DESCRIPTOR.message_types_by_name['TrainerServerRequest'] = _TRAINERSERVERREQUEST
DESCRIPTOR.message_types_by_name['TrainerServerResponse'] = _TRAINERSERVERRESPONSE
DESCRIPTOR.message_types_by_name['TrainingHyperparameters'] = _TRAININGHYPERPARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainerServerRequest = _reflection.GeneratedProtocolMessageType('TrainerServerRequest', (_message.Message,), {

  'ModelConfigurationEntry' : _reflection.GeneratedProtocolMessageType('ModelConfigurationEntry', (_message.Message,), {
    'DESCRIPTOR' : _TRAINERSERVERREQUEST_MODELCONFIGURATIONENTRY,
    '__module__' : 'trainer_server_pb2'
    # @@protoc_insertion_point(class_scope:trainer.TrainerServerRequest.ModelConfigurationEntry)
    })
  ,
  'DESCRIPTOR' : _TRAINERSERVERREQUEST,
  '__module__' : 'trainer_server_pb2'
  # @@protoc_insertion_point(class_scope:trainer.TrainerServerRequest)
  })
_sym_db.RegisterMessage(TrainerServerRequest)
_sym_db.RegisterMessage(TrainerServerRequest.ModelConfigurationEntry)

TrainerServerResponse = _reflection.GeneratedProtocolMessageType('TrainerServerResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINERSERVERRESPONSE,
  '__module__' : 'trainer_server_pb2'
  # @@protoc_insertion_point(class_scope:trainer.TrainerServerResponse)
  })
_sym_db.RegisterMessage(TrainerServerResponse)

TrainingHyperparameters = _reflection.GeneratedProtocolMessageType('TrainingHyperparameters', (_message.Message,), {
  'DESCRIPTOR' : _TRAININGHYPERPARAMETERS,
  '__module__' : 'trainer_server_pb2'
  # @@protoc_insertion_point(class_scope:trainer.TrainingHyperparameters)
  })
_sym_db.RegisterMessage(TrainingHyperparameters)


_TRAINERSERVERREQUEST_MODELCONFIGURATIONENTRY._options = None

_TRAINERSERVER = _descriptor.ServiceDescriptor(
  name='TrainerServer',
  full_name='trainer.TrainerServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=419,
  serialized_end=517,
  methods=[
  _descriptor.MethodDescriptor(
    name='start_training',
    full_name='trainer.TrainerServer.start_training',
    index=0,
    containing_service=None,
    input_type=_TRAINERSERVERREQUEST,
    output_type=_TRAINERSERVERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAINERSERVER)

DESCRIPTOR.services_by_name['TrainerServer'] = _TRAINERSERVER

# @@protoc_insertion_point(module_scope)
