"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TrainerServerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class ModelConfigurationEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.int
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    MODEL_ID_FIELD_NUMBER: builtins.int
    HYPERPARAMETERS_FIELD_NUMBER: builtins.int
    CHECKPOINT_PATH_FIELD_NUMBER: builtins.int
    MODEL_CONFIGURATION_FIELD_NUMBER: builtins.int
    model_id: builtins.str
    @property
    def hyperparameters(self) -> global___TrainingHyperparameters: ...
    checkpoint_path: builtins.str
    @property
    def model_configuration(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.int]: ...
    def __init__(
        self,
        *,
        model_id: builtins.str = ...,
        hyperparameters: global___TrainingHyperparameters | None = ...,
        checkpoint_path: builtins.str = ...,
        model_configuration: collections.abc.Mapping[builtins.str, builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["hyperparameters", b"hyperparameters"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["checkpoint_path", b"checkpoint_path", "hyperparameters", b"hyperparameters", "model_configuration", b"model_configuration", "model_id", b"model_id"]) -> None: ...

global___TrainerServerRequest = TrainerServerRequest

@typing_extensions.final
class TrainerServerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAINING_ID_FIELD_NUMBER: builtins.int
    training_id: builtins.int
    def __init__(
        self,
        *,
        training_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["training_id", b"training_id"]) -> None: ...

global___TrainerServerResponse = TrainerServerResponse

@typing_extensions.final
class TrainingHyperparameters(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BATCH_SIZE_FIELD_NUMBER: builtins.int
    LEARNING_RATE_FIELD_NUMBER: builtins.int
    batch_size: builtins.int
    learning_rate: builtins.float
    def __init__(
        self,
        *,
        batch_size: builtins.int = ...,
        learning_rate: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["batch_size", b"batch_size", "learning_rate", b"learning_rate"]) -> None: ...

global___TrainingHyperparameters = TrainingHyperparameters
