pipeline:
  name: abstaracts
  description: Training on wikipedia corpus
  version: 1.0.0
model:
  id: T5
model_storage:
  full_model_strategy:
    name: "PyTorchFullModel"
training:
  gpus: 1
  epochs_per_trigger: 2
  training_type: "generative"
  device: "cuda:1"
  dataloader_workers: 1
  use_previous_model: false
  initial_model: random
  #/tmp/models/ftp/2238241055_47_0.modyn
  batch_size: 8
  record_loss_every: 100
  shuffle: True
  amp: false
  grad_norm: 0.1
  optimizers:
    - name: "default"
      algorithm: "Adafactor"
      source: "HuggingFace"
      param_groups:
        - module: "model"
          config:
            lr: 0.0001
            scale_parameters: True
            relative_step: True
  lr_scheduler:
    step_every: "batch"
    name: "WarmupDecayLR"
    source: "Custom"
    optimizers: ["default"]
    config:
      total_num_steps: 80000 # Total training steps
      warmup_min_lr: 0          # Minimum learning rate at the start of warmup
      warmup_max_lr: 0.001         # Maximum learning rate after warmup
      warmup_num_steps:  8000 # Number of steps for the warmup phase
      warmup_type: "log"          # Type of warmup progression
      last_batch_iteration: -1

  optimization_criterion:
    name: "CrossEntropyLoss"
  checkpointing:
    activated: True
    interval: 1000
    path: "/checkpoints/abstracts_gen_eval"
data:
  dataset_id: abstracts_train_gen
  transformations: []
  bytes_parser_function: |
    import torch
    def bytes_parser_function(data: memoryview) -> torch.Tensor:
      text ="Summarize this abstract: "+str(data, 'utf8')
      return text
  bytes_parser_function_target: |
    import torch
    def bytes_parser_function(data: memoryview) -> torch.Tensor:
      text = str(data, 'utf8')
      return text
  tokenizer: "T5TokenizerTransform"
trigger:
  id: TimeTrigger
  every: "1y"
selection_strategy:
  name: NewDataStrategy
  maximum_keys_in_memory: 1000
  storage_backend: "database"
  limit: -1
  tail_triggers: 0
evaluation:
  handlers:
    - execution_time: after_training
      strategy:
        type: SlicingEvalStrategy
        eval_every: 1y
        eval_start_from: 315532800
        eval_end_at: 1744309156
      models: matrix
      datasets: ["abstracts_test_gen2"]

  device: "cuda:1"
  datasets:
    - dataset_id: abstracts_test_gen2
      generative: true
      transformations: []
      bytes_parser_function: |
        import torch
        def bytes_parser_function(data: memoryview) -> torch.Tensor:
          text ="Summarize this abstract: "+str(data, 'utf8')
          return text
      bytes_parser_function_target: |
        import torch
        def bytes_parser_function(data: memoryview) -> torch.Tensor:
          text = str(data, 'utf8')
          return text
      tokenizer: "T5TokenizerTransform"
      batch_size: 64
      dataloader_workers: 2
      metrics:
        - name: "Perplexity"
          generative: true
        - name: "Bleu"
          generative: true
          evaluation_transformer_function: |
            import torch
            def evaluation_transformer_function(model_output: torch.Tensor) -> torch.Tensor:
              return torch.argmax(model_output, dim=-1)
