pipeline:
  name: opensubtitles
  description: Training on wikipedia corpus
  version: 1.0.0
model:
  id: Gpt2
model_storage:
  full_model_strategy:
    name: "PyTorchFullModel"
training:
  gpus: 1
  epochs_per_trigger: 4
  generative: True
  device: "cuda:0"
  dataloader_workers: 1
  use_previous_model: false
  initial_model: random
  #/tmp/models/ftp/2238241055_47_0.modyn<
  batch_size: 64
  record_loss_every: 100
  shuffle: False
  amp: false
  lora: false
  grad_norm: 0.5
  optimizers:
    - name: "default"
      algorithm: "AdamW"
      source: "HuggingFace"
      param_groups:
        - module: "model"
          config:
            lr: 0.0001
            scale_parameters: False
            relative_step: False
  optimization_criterion:
    name: "CrossEntropyLoss"
  checkpointing:
    activated: True
    interval: 500
    path: "/checkpoints/mixreview10"
data:
  dataset_id: mixreview10
  transformations: []
  bytes_parser_function: |
    import torch
    def bytes_parser_function(data: memoryview) -> torch.Tensor:
      text = str(data, 'utf8')

      # Remove surrounding quotes if they exist
      if text.startswith('"') and text.endswith('"'):
          text = text[1:-1]

      return text
  tokenizer: "GPT2TokenizerTransform"
trigger:
  id: DataAmountTrigger
  num_samples: 2000
selection_strategy:
  name: NewDataStrategy
  maximum_keys_in_memory: 500
  storage_backend: "database"
  limit: -1
  tail_triggers: 0
