# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: preprocess.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10preprocess.proto\x12\npreprocess\"\"\n\x11PreprocessRequest\x12\r\n\x05value\x18\x01 \x03(\x0c\"\x14\n\x12PreprocessResponse2[\n\nPreprocess\x12M\n\nPreprocess\x12\x1d.preprocess.PreprocessRequest\x1a\x1e.preprocess.PreprocessResponse\"\x00\x62\x06proto3')  # noqa: E501

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'preprocess_pb2', globals())
if not _descriptor._USE_C_DESCRIPTORS:

    DESCRIPTOR._options = None
    _PREPROCESSREQUEST._serialized_start = 32
    _PREPROCESSREQUEST._serialized_end = 66
    _PREPROCESSRESPONSE._serialized_start = 68
    _PREPROCESSRESPONSE._serialized_end = 88
    _PREPROCESS._serialized_start = 90
    _PREPROCESS._serialized_end = 181
# @@protoc_insertion_point(module_scope)
