runs:
  using: "composite"
  steps: 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        shell: bash
      
      # increase to reset cache manually
      - name: Set cache number
        run: echo "CACHE_NUMBER=6" >> $GITHUB_ENV 
        shell: bash

      - name: Get conda path
        run: echo "CONDAPATH=/usr/share/miniconda/envs" >> $GITHUB_ENV 
        shell: bash

      - name: Fix directory permissions
        run: sudo chown -R $(whoami):$(id -ng) ${CONDAPATH}
        shell: bash

      - uses: actions/cache@v3
        with:
          path: ${{ env.CONDAPATH }}
          key: conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Setup requirements
        run: |
          conda update -n base -c defaults conda
          conda update --all
          conda env create -f ./environment.yml
          conda run -n modyn pip install -r dev-requirements.txt
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash

      - name: Reinstall modyn in case of cache
        run: conda run -n modyn pip install -e .
        if: steps.cache.outputs.cache-hit == 'true'
        shell: bash