name: Modyn base action

defaults:
  run:
    shell: bash

runs:
  steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build Docker modyn image
      run: docker build --progress=plain -t modyn -f docker/Base/Dockerfile .