runs:
  using: "composite"
  steps: 
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2
    
    # Necessary to e.g. patch which container image is being used
    - name: Apply initial setup
      run: |
        bash ./initial_setup.sh
      shell: bash

    - name: Temporary print of dockerfile
      run: |
         cat ./docker/Dependencies/Dockerfile
      shell: bashs

    - name: Build dependencies and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/Dependencies/Dockerfile
        tags: modyndependencies
        outputs: type=docker,dest=/tmp/modyndependencies.tar
        cache-from: type=gha
        cache-to: type=gha

    - name: Load base image locally
      run: |
        docker load --input /tmp/modyndependencies.tar
        docker image ls -a
      shell: bash

    - name: Build base image
      run: |
        docker build -t modynbase -f docker/Base/Dockerfile .
      shell: bash


