runs:
  using: "composite"
  steps: 
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build dependencies and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./docker/Dependencies/Dockerfile
        tags: modyndependencies
        cache-from: type=gha
        cache-to: type=gha

    - name: Build base and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./docker/Base/Dockerfile
        tags: modyn
        outputs: type=docker,dest=/tmp/modynbase.tar
        cache-from: type=gha
        cache-to: type=gha

    - name: Load base image locally
      run: |
        docker load --input /tmp/modynbase.tar
        docker image ls -a
      shell: bash
