version: '3.4'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default_database
    ports:
      - '5432:5432'
    volumes: 
          - ./postgres-data:/var/lib/postgresql/data
  storage:
    image: storage
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./dynamicdatasets/storage/Dockerfile
  newqueue:
    image: newqueue
    build:
      context: ./
      dockerfile: ./dynamicdatasets/newqueue/Dockerfile
  preprocess:
    image: preprocess
    build:
      context: ./
      dockerfile: ./dynamicdatasets/preprocess/Dockerfile
  odm:
    image: odm
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./dynamicdatasets/odm/Dockerfile

  input:
    image: input
    depends_on:
      - db
      - storage
      - newqueue
      - preprocess
    build:
      context: ./
      dockerfile: ./dynamicdatasets/input/Dockerfile