version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default_database
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  storage-db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./storage/internal/database/.env
    ports:
      - '50060:50060'
    volumes:
      - ./storage-postgres-data:/var/lib/postgresql/data

  storage:
    image: storage
    depends_on:
      - storage-db
    build:
      context: ../
      dockerfile: modyn/storage/Dockerfile
    ports:
      - '50051:50051'
    volumes:
      - ./modyn/storage:/app
