# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: odm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\todm.proto\x12\x03odm\" \n\x10GetByKeysRequest\x12\x0c\n\x04keys\x18\x01 \x03(\t\"\"\n\x11GetByQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"9\n\x0bGetResponse\x12\x0c\n\x04keys\x18\x01 \x03(\t\x12\x0e\n\x06scores\x18\x02 \x03(\x02\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\t\"\x1f\n\x0fGetKeysResponse\x12\x0c\n\x04keys\x18\x01 \x03(\t\"8\n\nSetRequest\x12\x0c\n\x04keys\x18\x01 \x03(\t\x12\x0e\n\x06scores\x18\x02 \x03(\x02\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\t\"\r\n\x0bSetResponse2\xe5\x01\n\x03ODM\x12\x36\n\tGetByKeys\x12\x15.odm.GetByKeysRequest\x1a\x10.odm.GetResponse\"\x00\x12\x38\n\nGetByQuery\x12\x16.odm.GetByQueryRequest\x1a\x10.odm.GetResponse\"\x00\x12@\n\x0eGetKeysByQuery\x12\x16.odm.GetByQueryRequest\x1a\x14.odm.GetKeysResponse\"\x00\x12*\n\x03Set\x12\x0f.odm.SetRequest\x1a\x10.odm.SetResponse\"\x00\x62\x06proto3')  # noqa: E501

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'odm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETBYKEYSREQUEST._serialized_start=18
  _GETBYKEYSREQUEST._serialized_end=50
  _GETBYQUERYREQUEST._serialized_start=52
  _GETBYQUERYREQUEST._serialized_end=86
  _GETRESPONSE._serialized_start=88
  _GETRESPONSE._serialized_end=145
  _GETKEYSRESPONSE._serialized_start=147
  _GETKEYSRESPONSE._serialized_end=178
  _SETREQUEST._serialized_start=180
  _SETREQUEST._serialized_end=236
  _SETRESPONSE._serialized_start=238
  _SETRESPONSE._serialized_end=251
  _ODM._serialized_start=254
  _ODM._serialized_end=483
# @@protoc_insertion_point(module_scope)
