# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metadata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emetadata.proto\x12\x08metadata\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x1a\n\x07\x42\x61tchId\x12\x0f\n\x07\x62\x61tchId\x18\x01 \x01(\x05\"+\n\x05\x42\x61tch\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x04rows\x18\x02 \x03(\x05\x42\x02\x10\x01\"5\n\tBatchData\x12(\n\x07\x64\x61taMap\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2w\n\x08Metadata\x12\x30\n\x08\x41\x64\x64\x42\x61tch\x12\x0f.metadata.Batch\x1a\x11.metadata.BatchId\"\x00\x12\x39\n\x08GetBatch\x12\x16.google.protobuf.Empty\x1a\x13.metadata.BatchData\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metadata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BATCH.fields_by_name['rows']._options = None
  _BATCH.fields_by_name['rows']._serialized_options = b'\020\001'
  _BATCHID._serialized_start=87
  _BATCHID._serialized_end=113
  _BATCH._serialized_start=115
  _BATCH._serialized_end=158
  _BATCHDATA._serialized_start=160
  _BATCHDATA._serialized_end=213
  _METADATA._serialized_start=215
  _METADATA._serialized_end=334
# @@protoc_insertion_point(module_scope)
