name: Build Dependencies

on:
  schedule:
    - cron: '0 0 1 * *'  # Run at midnight on the first of every month
  workflow_dispatch:
  pull_request:  # TODO: remove once fully implemented

jobs:
  build_grpc:
    name: Build gRPC artifacts
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check out codebase
        uses: actions/checkout@v4
